apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transaction
  template:
    metadata:
      labels:
        app: transaction
    spec:
      containers:
      - name: transaction-container
        image: sanjeeva121/transaction-service:1.0
        ports:
        - containerPort: 5000
